sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: dskAXnIlTKbdTHfS0SPmFOlOyPjPhOsxWp6BBFqoYIgpG9nqXMxpc1dE/CSxp83aaIJLlKCJgV62K8qByn5Q9c1x6SLNKkJXh25PTKyTBYxlAAqCopgV9dsBDBmSjvW8epoDtmbE6yTeMgBJBPyPJu26boyP5Gg+zxFyEDPGljRJLEnG0wJzsZHhQ4qqhIQr4fZJcude42bIkiqEnBa3c4ywNLevtp8LH/G1VPZ4OLdo/NdiGbILBifhzD7vJ9yGLUd0nfHbcJvd4+Qbf0c39neJTOj2nRpUId7GlBvtC5gYOqa8gRY1zvfVJ/1nIiaupb8n247mrXxKfc6XRqvhASpzatpnW1rkTMJimG6VzySusu/CNio/V2sG/0PgXAL5kF1pNXe86OKV9EDuCnlFx9gihPGPRi4lpmXhQFDwOm6O+iRaxaYcgZfgCBXbk0RlgXik3WZ+rqziVALmJSKlTmpLH/tisBIoA0yLozDYZYFW8nBHwdi9vrTi7eLe5amT5ML4ZQmYrQ6vFoL9sEoVsBvHDSFLZEDn3uyOjJ5FE0Wn2wPoxiu35xilZcqCaWeBAAZ7Snpwq7xUC0V0YHiDF5bWQzTLP7uYR7qDzEfRSNMBxi/NuOhnfJx1X2bM+JiS2q4jTtbxaNl1IGrRuJgCZUSHfrpu01lmzRVK44LDAYM=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: zd/ZNPIpwXwsGUW7yRVoHlWQEgQtQe/uXe5U+VJCSW2mDuRL4Fn9udyTpGxtUVTvUOwn2Eilih14xHUZarfxujxkXzUCEt/Zf64KXZtZaMDWLq0Z5hUs4PcAeC2GycJREgyc8atIvtiRXVAGxbSKvf9gibT1J5QIc60OJr8nZzYxgoyMat1G7JzSENamFgzRgOCbLLuQoJapCLmgzS1wNtQcsAZYo5PC9+2vJ/xpd+i1/+r3pGK70Ge/53NOqpZ8NN+9knK47IdnmZaJhA4JPi95lt2JjiBmkz9T2DYjVzkgBHX19QjFUfiLKz85pEK5/Vt781fzTjQEmSmpDQd+D4kfVXbIKv5uMV3iygsYUtU4tdpjmRkvP8qjkGorETo/U5I7+2+uplUZV/oVftiXDx0fgxeol/Yn5WNY9C9IDbllwOhpAvfuzfRfbl9kbIPVh0l/9AjCMyqPMWHT6mqxKSy1EwjU1Hfg+jj/i9+jvJhP1OtCV94ZQqeFzN8NjEBpXiu0v39MrD5hy0NytANF/PnyA/vtro1oNDahkhsMnTMgMFiVa5QPll+m0k2guL+MsYgM0jSUwrp7Y0g8v+RarjiH1zMTarRoo0EWrMGrqXY8Ihup9KwAHiKQpQdVFL/UTo9pHf4vQOIOjWsCcXGYdvYPCOpZ10ZIht/jzfPw9WE=
